@startuml

autonumber
actor Player
boundary PlayerBoundary
entity GameController

PlayerBoundary -> GameController: EndGame(gameId)
database GameList
GameController -> GameList: isGameExist(gameId)
entity Game

alt Game with id exists
    GameList -> GameController: Game
    alt Game Player <=1
        GameController->GameList: removeGame()
    else Game Players> 1
        GameController -> GameList: updateGame(gameId)
        GameController -> PlayerBoundary: Player left the game response message
    end
    GameController -> Game: endGame()
else Game with id not found
    GameList -> GameController: Game not found(null)
    GameController -> PlayerBoundary: Game not found error message
end


@enduml