@startuml

title End Game Sequence Diagram

autonumber
actor Player
boundary AngularUI
entity GameController

AngularUI -> GameController: endGame(gameId)
database GameList
GameController -> GameList: isGameExist(gameId)
entity Game

alt Game with id exists
    GameList -> GameController: Game
    GameController -> Game: endGame()
    Game -> GameController: ok
    GameController -> GameList: updateGame(gameId)
    GameController -> AngularUI: Player left the game broadcast notification message
    alt Game Player <=1
        note over GameList: Perform cleanup service
        GameController -> GameList: removeGame(gameId)
        GameList -> GameController: ok
        GameController -> AngularUI: Game session ended notification message
    end

else Game with id not found
    GameList -> GameController: Game not found(null)
    GameController -> AngularUI: Game not found error message
end


@enduml