@startuml

autonumber
actor Player
boundary PlayerBoundary
entity GameController
PlayerBoundary -> GameController: joinGame(gameId, userId, playerName)
database GameList
entity Game
GameController -> GameList: isGameExist(gameId)

alt Game with id exists
    GameList -> GameController: Game
    GameController -> Game: userJoin(userId)
    GameController -> Game: getUserPlayer(userId)
    Game -> GameController: PlayerData
    GameController -> PlayerBoundary: PlayerData

else User can't join the game (character is already taken)
    GameList -> GameController: Game
    GameController -> Game: userJoin(userId)
    GameController -> PlayerBoundary: Character already selected error message

else Game with id not found
    GameList -> GameController: Game not found(null)
    GameController -> PlayerBoundary: Game not found error message
end
@enduml