@startuml

title Join Game Sequence Diagram

autonumber
actor Player
boundary AngularUI
entity GameController
AngularUI -> GameController: joinGame(gameId, userId, playerName)
database GameList
entity Game
GameController -> GameList: isGameExist(gameId)

alt Game with id exists
    GameList -> GameController: Game
    GameController -> Game: userJoin(userId)
    GameController -> Game: getUserPlayer(userId)
    Game -> GameController: PlayerData
    GameController -> AngularUI: PlayerData

else User can't join the game (character is already taken)
    GameList -> GameController: Game
    GameController -> Game: userJoin(userId)
    GameController -> GameList: update Game with gameId
    GameController -> AngularUI: Character already selected error message

else Game with id not found
    GameList -> GameController: Game not found(null)
    GameController -> AngularUI: Game not found error message
end
@enduml