@startuml

title Accusation Mechanism Sequence Diagram

autonumber
actor Player
boundary AngularUI
entity GameController

AngularUI -> GameController: makeAccusation(gameId, userId, accusedPlayerId,weaponType,room)
database GameList
entity GameService
entity Games
GameController -> GameList: isGameExist(gameId)

alt Game with id exists
    GameList -> GameController: Game
    GameController -> GameService: makeAccusation(Game, userId, accusedPlayerId, weaponType, room)
    alt Accusation is valid
        GameService-> Game: checkAccusation(accusedPlayerId, weaponType, room)
        group Accusation is Correct
            Game -> GameService: ok
            GameController -> AngularUI: Player has won end game
            GameController -> AngularUI: Broadcast notification with Player's accusation
            GameController -> GameService: endGame(gameId)
        end
    else
        group Accusation is Incorrect
            Game -> GameService: fail
            GameService -> Game: markPlayerLost(userId)
            GameService -> GameController: error message
            GameController -> AngularUI: Skip turn and notify user of wrong accusation
        end
    end
else Game with id not found
    GameList -> GameController: Game not found(null)
    GameController -> AngularUI: Game not found error message
end
@enduml