@startuml

autonumber
actor Player
boundary PlayerBoundary
entity GameController

PlayerBoundary -> GameController: makeAccusation(gameId, userId, accusedPlayer)
database GameList
entity GameService
entity Games
GameController -> GameList: isGameExist(gameId)

alt Game with id exists
    GameList -> GameController: Game
    GameController -> GameService: makeAccusation(gameId, userId, accusedPlayer)
    alt Accusation is valid
        GameController -> PlayerBoundary: Broadcast notification with Player's accusation
        GameService->Game: CheckAccusation(accusedPlayer)
        GameService-> GameController: Accusation =True or False
        group Accusation is Correct
            GameController -> PlayerBoundary: Player has won end game
            GameController -> Game: endGame()
        end
    else
        group Accusation is Incorrect
            GameController -> PlayerBoundary: Skip turn
            
        end
    end
else Game with id not found
    GameList -> GameController: Game not found(null)
    GameController -> PlayerBoundary: Game not found error message
end
@enduml