@startuml

autonumber
actor Player
boundary PlayerBoundary
entity GameController

PlayerBoundary -> GameController: moveCharacter(gameId, userId, direction)
database GameList
entity GameService
entity Game
GameController -> GameList: isGameExist(gameId)

alt Game with id exists
    GameList -> GameController: Game
    GameController -> GameService: moveCharacter(Game, userId, direction)
    alt direction is valid
        group Movement Success
            GameService -> Game: Update Player with userId's coordinates
            GameService -> GameList: updateGame(gameId)
            GameService -> GameController: ok
            GameService -> GameController: disable player with userId's turn
            alt Player makes Accusation
                GameService->GameList:updatePlayerAccusation(Player, Accused_Player)
            end
            GameService -> GameController: enable next player's turn
            GameController -> PlayerBoundary: Broadcast notification with Player's current coordinates and accusation
        end
    else
        group Movement Failure
            GameService -> GameController: fail
            GameController -> PlayerBoundary: movement failure message with reason
        end
    end
else Game with id not found
    GameList -> GameController: Game not found(null)
    GameController -> PlayerBoundary: Game not found error message
end
@enduml