@startuml

title Start Game Sequence Diagram

autonumber
actor Player
boundary AngularUI
entity GameController

AngularUI -> GameController: startGame(gameId)
database GameList
GameController -> GameList: isGameExist(gameId)
entity Game

alt Game with id exists
    GameList -> GameController: Game
    GameController -> Game: startGame()
    GameController -> GameList: updateGame(gameId)
    GameController -> AngularUI: Game started broadcast notification message

else Game with id not found
    GameList -> GameController: Game not found(null)
    GameController -> AngularUI: Game not found error message
end

@enduml