@startuml
'https://plantuml.com/sequence-diagram

title Suggestion Mechanism Sequence Diagram

autonumber
actor Player
boundary AngularUI
entity GameController
entity GameService
database GameList
AngularUI -> GameController: makeSuggestion(gameId, playerId, otherPlayerId, weaponId, roomXY)
GameController -> GameList: isGameExist(gameId)
entity Game
database WeaponDB

alt Game with id exists
    GameController -> GameService: makeSuggestion(game, playerId, otherPlayerId, weaponId, roomXY)
    GameList -> GameService: Game
    GameService -> WeaponDB: getWeapon(weaponId)
    WeaponDB -> GameService: Weapon
    GameService -> ClueMap: roomXY
    ClueMap -> GameService: Room
    alt Player making suggestion is in the same room
        note over Game: Update the coordinates for otherPlayerId to that of the room
        GameService -> Game: makeSuggestion(playerId, otherPlayerId, weapon, room)
        note over GameService: Disable Suggestion action for user with playerId
        GameService -> Game: disablePlayerActions(playerId, actionType)
        GameService -> GameController: ok
        GameController -> AngularUI: Broadcast notification
    else Player making suggestion is not in the same room
        GameService -> GameController: fail
        GameController -> AngularUI: Failure message with reason
    end

else Game with id not found
    GameList -> GameController: Game not found(null)
    GameController -> AngularUI: Game not found error message
end
@enduml